### ISSUE TITLE
Connecting with Ledger Cosmos app

### ISSUE THREAD

**Issue by WorkerB33** [terra-money/bridge-web-app#105]
Up until a today (Dec/21/2021) I have been able to connect to Terrastation using Cosmos app. My entire wallet address for terra is in there. I use that one to connect Terra to Cosmos network. Would you be able to allow me to connect using my cosmos app again?

**Comment by WorkerB33** [comment]
https://medium.com/osmosis-community-support-dao/transferring-ust-from-osmosis-to-terrastation-ffa0df3dc435

I also created this article about connecting UST from Osmosis to TerraStation. Option 3 was my route that I used for myself. 

If you can't I'll understand but I'm hoping there is a chance.

**Comment by alecande11** [comment]
Cosmos path is no longer supported, please use https://legacy.station.terra.money to move everything to the terra ledger app
