### ISSUE TITLE
'Destination address' field not controlled per chain.

### ISSUE THREAD

**Issue by Cordtus** [terra-money/bridge-web-app#106]
Just a small thing I noticed as an everyman after trying to help someone find out why their transaction went wrong. They were attempting to send LUNA from Terra to Osmosis but they accidentally entered their cosmos address in the destination field. As far as I know, as it stands it is not possible to send (fuunctional) non-native tokens from chain to chain other than to or from their native chain, so this incorrect address should not be possible to even attempt with this tool.

**Comment by devhyunjae** [comment]
Thanks, fixed by #108
