### ISSUE TITLE
Issue moving ust from Harmony to Terra

### ISSUE THREAD

**Issue by mrwokecoin** [terra-money/bridge-web-app#109]
Hello, I tried moving UST from Harmony to Terry using Terra Bridge. It shows success on Harmony explorer but the funds never arrived on Terra. The Harmony hash id is below. Is there anything I can do to fix this?

https://explorer.harmony.one/tx/0xbafef3f653a030c4a63319708d708fc5337c4b47b5b63eabd4d094a2f6be3cb0

**Comment by OverflowIDK** [comment]
Hello Terra team, 
The same happened to me few days ago, but on my case I have executed two transactions, one [transaction that executed correctly](https://explorer.harmony.one/tx/0xba20cd8b4ed2fd37bd38e0372161a69970ea5b8348da26b90f3aefb7a6b57aa4) and [another transaction](https://explorer.harmony.one/tx/0xd10e18c1cb16b856fd5fe84f7702d225ee25d8d9b95d2239fa167af214160e6b
) that I cannot see on Terras blockchain but on harmony was correctly executed (there are 3 min of difference between the two transactions).

Thanks for taking a look on them, if you need some more inside or help to debug please let me know I can support you.

**Comment by mestresecreto** [comment]
Did the UST arrive?

**Comment by Mekcukahell** [comment]
Same problem. I have been waiting for the eighth hour for the receipt of the coin. I used the Harmony-Terra bridge. The coin was burned, but not credited ... Can I somehow solve it?

https://explorer.harmony.one/tx/0x9533feb09da53d93b9f247aab065b7732ab678318cd49eb06bd023fd5ce20e38

**Comment by emidev98** [comment]
If it take more than some minutes go to discord, they will help, the comunity is very good

**Comment by alecande11** [comment]
for tx recovery on harmony check out the Terra discord group
