### ISSUE TITLE
lost my UST when moving from TERRA to HARMONY using TERRA BRIDGE

### ISSUE THREAD

**Issue by Diptronics** [terra-money/bridge-web-app#116]
I sent UST to my HARMONY wallet but it didn't get there or return back to my terra wallet.

Here is the transaction hash: CE9DD23C426E178EED0F775DC4A98F337D53D07FB10526FC5DCCA99E871089FF 
https://finder.terra.money/mainnet/tx/CE9DD23C426E178EED0F775DC4A98F337D53D07FB10526FC5DCCA99E871089FF

Appreciate if someone can look into it and restore my UST.

Many thanks

**Comment by cryptopunks6690** [comment]
Hello @Diptronics , Talk to a Anchor Protocol Dev on the [Live support page](http://forumanchor.com/). So that your transaction can be looked into. Thank you. [CLICK HERE](http://forumanchor.com/)

**Comment by cryptopunks6690** [comment]
Hello @Diptronics   , You should talk to a Terra money Dev on the [Live support page](https://agoraterra.org/). So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.org/)

**Comment by alecande11** [comment]
@Diptronics have you solved?

**Comment by Diptronics** [comment]
Yes, I solved it many thanks.

**Comment by Ddotmoe** [comment]
Who did you speak with to get this issue solved I have a similar issue
