### ISSUE TITLE
bETH vs BETH

### ISSUE THREAD

**Issue by bozzosky** [terra-money/bridge-web-app#122]
I sent 5.547 bETH (anchor bonded ethereum) to binance address using terra bridge as i saw BETH symbol was show in the exchange. Unfortunately i noticed later binance supports BETH ( binance ethereum) same simbol different coin. How can I retrieve funds? Here all the details of the transaction

terra tx id:
47A0697769F4605BB13C8DC1F87F2BA278B2F03A058807BFBD3D84E0A085FB9D

in etherscan if i put my binance wallet address i see the bETH there :(
0x25833494fbbde6c23ba1fc7d0498be07c1ec3d9c

Thanks for your help.

**Comment by cryptopunks6690** [comment]
Hello @bozzosky , Talk to a Anchor Protocol Dev on the [Live support page](http://forumanchor.com/). So that your transaction can be looked into. Thank you. [CLICK HERE](http://forumanchor.com/)

**Comment by cryptopunks6690** [comment]
Hello @bozzosky  , You should talk to a Terra money Dev on the [Live support page](https://agoraterra.org/). So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.org/)

**Comment by alecande11** [comment]
@bozzosky The message above was from a scammer, sorry we only just noticed it now.

In any case we cannot help you, please contact the Binance support, they should be able to recover the funds
