### ISSUE TITLE
Trying to figure out where my Luna went

### ISSUE THREAD

**Issue by mbfgithub** [terra-money/bridge-web-app#131]
I tried to send 1 Luna from terra to my osmosis address but I can't figure out where the 1 Luna went. It went out of my terra wallet but is not in my osmosis wallet.
64EB626EF87545883BB9A5054F216E967A7CB77FA9D390096F5D0656E6BE0B69

**Comment by Mary-dev-a** [comment]
Hello @mbfgithub Kindly chat with one of our support on live chat to get a quicker response [CLICK HERE](https://agora-terra.org/)

**Comment by alecande11** [comment]
You have received them https://www.mintscan.io/osmosis/txs/6D7BED63C869AE818FE114C5A81C58608CF77298DE228A303C9E303943EA0FCB
