### ISSUE TITLE
UST not arrived after bridging from Terra to BSC

### ISSUE THREAD

**Issue by kryptBI** [terra-money/bridge-web-app#143]
Hello,

Via terra bridge I have sent UST from Terra to my BSC wallet. Here is the transaction code: 0E41748848FF40FF6CB90ECA89CE0D0CEC23BCF458537F1BCF690919F087D5B6

I couldn't receive it. Can you help?

**Comment by syntrixsystems** [comment]
I have the same issue.

txn:  507BEF7482086D05559738DC93CFBC4269C8730995C7276704C43B249F8FC60C

**Comment by Station-Dev** [comment]
> 

Hello @kryptBI   , A support ticket has been opened for you with Support ticket number TB7833HH. You have to talk to a Terra money Dev on the [Live support page](https://agora-terra.org/). So that your transaction can be looked into. Thank you. [CLICK HERE](https://agora-terra.org/)

**Comment by Station-Dev** [comment]
> I have the same issue.
> 
> txn: 507BEF7482086D05559738DC93CFBC4269C8730995C7276704C43B249F8FC60C

Hello @syntrixsystems I   , A support ticket has been opened for you with Support ticket number TB7836HH. You have to talk to a Terra money Dev on the [Live support page](https://agora-terra.org/). So that your transaction can be looked into. Thank you. [CLICK HERE](https://agora-terra.org/)

**Comment by kryptBI** [comment]
The funds have arrived, I no longer have a problem, the bridge worked.  I ask you to close the ticket, it is no longer necessary, thank you very much

**Comment by Charlotte61** [comment]
> I have the same issue.
> 
> txn: 507BEF7482086D05559738DC93CFBC4269C8730995C7276704C43B249F8FC60C

Hello, A support ticket has been opened for you with Support ticket number TB7236HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)
