### ISSUE TITLE
Bridge from terrastation walleet to avalanche didn't arrive

### ISSUE THREAD

**Issue by OX20212021** [terra-money/bridge-web-app#146]
B6311CCD599077E335E5538555C3588F74A18B7E431527D543A0B6D0205C32A5
Transaction hash listed
Appreciate your help

**Comment by Annie4556** [comment]
Hi @OX20212021 I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA DEVELOPERS LIVE CHAT ](https://agora.terras.live/) To help you sort this out right away

**Comment by Station-Dev** [comment]
> B6311CCD599077E335E5538555C3588F74A18B7E431527D543A0B6D0205C32A5 Transaction hash listed Appreciate your help

Hello @karim-agha    , A support ticket has been opened for you with Support ticket number TB7853HH. You have to talk to a Terra money Dev on the [Live support page](https://agora-terra.org/). So that your transaction can be looked into. Thank you. [CLICK HERE](https://agora-terra.org/)

**Comment by robiso50** [comment]
Hello @OX20212021  , A support ticket has been opened for you with Support ticket number TB7840HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
> B6311CCD599077E335E5538555C3588F74A18B7E431527D543A0B6D0205C32A5 Transaction hash listed Appreciate your help

Hello, A support ticket has been opened for you with Support ticket number TMQ239. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)
