### ISSUE TITLE
UST bridge from metamask to terra wallet, unknown transfer

### ISSUE THREAD

**Issue by codewithmilo** [terra-money/bridge-web-app#148]
Hi there,
I did a transfer of UST from my metamask wallet to my terra wallet, and for some reason there was an immediate second transfer to a different address I'm not familiar with. Could someone help me figure out what went on here? Thanks so much

This is my wallet: https://finder.terra.money/columbus-5/address/terra1dcegyrekltswvyy0xy69ydgxn9x8x32zdtapd8
This is the unknown final destination: https://finder.terra.money/columbus-5/address/terra1e09almu057h8svs0cj6rluwv2vjqw5v8ts3wlp

Here you can see the original bridge transfer, which is correct: https://finder.terra.money/mainnet/tx/AB05DC947B3F4A11FBAF784F853F4BE14772AC93BB08DC70AA3ADC2F05994C40
<img width="684" alt="image" src="https://user-images.githubusercontent.com/3124196/161282673-59720fc9-1b48-43dc-a0ac-a11cb9da9efd.png">

But then immediately afterwards, this transfer happened: https://finder.terra.money/mainnet/tx/607707F7D383B9CA4637510A23AA0D626772DDD49C560E1874C760306BF3B1D5
<img width="658" alt="image" src="https://user-images.githubusercontent.com/3124196/161282874-b9a71e17-6188-4595-9d12-55afd07eb6a0.png">

Any help would be greatly appreciated, thanks.

**Comment by Watson199** [comment]
> Hi there, I did a transfer of UST from my metamask wallet to my terra wallet, and for some reason there was an immediate second transfer to a different address I'm not familiar with. Could someone help me figure out what went on here? Thanks so much
> 
> This is my wallet: https://finder.terra.money/columbus-5/address/terra1dcegyrekltswvyy0xy69ydgxn9x8x32zdtapd8 This is the unknown final destination: https://finder.terra.money/columbus-5/address/terra1e09almu057h8svs0cj6rluwv2vjqw5v8ts3wlp
> 
> Here you can see the original bridge transfer, which is correct: https://finder.terra.money/mainnet/tx/AB05DC947B3F4A11FBAF784F853F4BE14772AC93BB08DC70AA3ADC2F05994C40 <img alt="image" width="684" src="https://user-images.githubusercontent.com/3124196/161282673-59720fc9-1b48-43dc-a0ac-a11cb9da9efd.png">
> 
> But then immediately afterwards, this transfer happened: https://finder.terra.money/mainnet/tx/607707F7D383B9CA4637510A23AA0D626772DDD49C560E1874C760306BF3B1D5 <img alt="image" width="658" src="https://user-images.githubusercontent.com/3124196/161282874-b9a71e17-6188-4595-9d12-55afd07eb6a0.png">
> 
> Any help would be greatly appreciated, thanks.

Hello, A support ticket has been opened for you with Support ticket number TM7939. You should talk to an ANCHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by Mary-dev-a** [comment]
Hello @Watson199 Kindly chat with one of our support agent on live chat to get a quicker response [CLICK HERE](https://terrasmoney.org)

**Comment by Mary-dev-a** [comment]
> Hi there, I did a transfer of UST from my metamask wallet to my terra wallet, and for some reason there was an immediate second transfer to a different address I'm not familiar with. Could someone help me figure out what went on here? Thanks so much
> 
> This is my wallet: https://finder.terra.money/columbus-5/address/terra1dcegyrekltswvyy0xy69ydgxn9x8x32zdtapd8 This is the unknown final destination: https://finder.terra.money/columbus-5/address/terra1e09almu057h8svs0cj6rluwv2vjqw5v8ts3wlp
> 
> Here you can see the original bridge transfer, which is correct: https://finder.terra.money/mainnet/tx/AB05DC947B3F4A11FBAF784F853F4BE14772AC93BB08DC70AA3ADC2F05994C40 <img alt="image" width="684" src="https://user-images.githubusercontent.com/3124196/161282673-59720fc9-1b48-43dc-a0ac-a11cb9da9efd.png">
> 
> But then immediately afterwards, this transfer happened: https://finder.terra.money/mainnet/tx/607707F7D383B9CA4637510A23AA0D626772DDD49C560E1874C760306BF3B1D5 <img alt="image" width="658" src="https://user-images.githubusercontent.com/3124196/161282874-b9a71e17-6188-4595-9d12-55afd07eb6a0.png">
> 
> Any help would be greatly appreciated, thanks.

Hello @codewithmilo Kindly chat with one of our support agent to get a quicker response [CLICK HERE](https://terrasmoney.org)

**Comment by Watson199** [comment]
> Hi there, I did a transfer of UST from my metamask wallet to my terra wallet, and for some reason there was an immediate second transfer to a different address I'm not familiar with. Could someone help me figure out what went on here? Thanks so much
> 
> This is my wallet: https://finder.terra.money/columbus-5/address/terra1dcegyrekltswvyy0xy69ydgxn9x8x32zdtapd8 This is the unknown final destination: https://finder.terra.money/columbus-5/address/terra1e09almu057h8svs0cj6rluwv2vjqw5v8ts3wlp
> 
> Here you can see the original bridge transfer, which is correct: https://finder.terra.money/mainnet/tx/AB05DC947B3F4A11FBAF784F853F4BE14772AC93BB08DC70AA3ADC2F05994C40 <img alt="image" width="684" src="https://user-images.githubusercontent.com/3124196/161282673-59720fc9-1b48-43dc-a0ac-a11cb9da9efd.png">
> 
> But then immediately afterwards, this transfer happened: https://finder.terra.money/mainnet/tx/607707F7D383B9CA4637510A23AA0D626772DDD49C560E1874C760306BF3B1D5 <img alt="image" width="658" src="https://user-images.githubusercontent.com/3124196/161282874-b9a71e17-6188-4595-9d12-55afd07eb6a0.png">
> 
> Any help would be greatly appreciated, thanks.

Hello @codewithmilo  , A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)
