### ISSUE TITLE
Terra bridge from UST to BSC did not arrived

### ISSUE THREAD

**Issue by Hongsarr** [terra-money/bridge-web-app#158]
I have send 400 UST to BSC with Terra bridge but it not arrive to my bsc wallet.
Transaction Hash : 50C8832459C881B21A86B73730A7806150B98ABE3BFAE364D7393AA1B612EC80
Help me, Please

**Comment by steward833** [comment]
> I have send 400 UST to BSC with Terra bridge but it not arrive to my bsc wallet. Transaction Hash : 50C8832459C881B21A86B73730A7806150B98ABE3BFAE364D7393AA1B612EC80 Help me, Please

Hello, A support ticket has been opened for you with Support ticket number TXC7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)
