### ISSUE TITLE
I transferred 1,916.430747 UST from BSC to TERRA, but Terra address do not receive UST

### ISSUE THREAD

**Issue by yuyan1991** [terra-money/bridge-web-app#172]
Transaction Date Time: May-11-2022 08:28:45 AM +UTC
BSC Transaction Hash: 0x527efaa715a5c973cfc053c2f5fae08fd9bfa211cba635d59044092729de61c2
Terra Address: terra1h958pz06w8chaagclv24z2083x2npgd4659h3p

Thanks a lot!

**Comment by creativefull** [comment]
i also bridge a lot ust but never received my money : 

**6,354**.949405 UST = https://bscscan.com/tx/0x07fec9e91050ff2d208dbb3770618e4782c90022c9d803beb7e615f237404f89
**8,474**.860373  UST = https://bscscan.com/tx/0xd6fcc144bc1a326532b0b8141d00ec0ac419bde3d1db107918d7ec50513c2b67
**2,010**.980757  UST = https://bscscan.com/tx/0x4e51c58583219555d462082695db04cea11eb505cc071734fcd948f5f26d9ff4

my terra address : terra1alq27zlll8at9cv0g059ypf8wqf6q2sdg5j8ta

**Comment by sammiyee** [comment]
> Transaction Date Time: May-11-2022 08:28:45 AM +UTC BSC Transaction Hash: 0x527efaa715a5c973cfc053c2f5fae08fd9bfa211cba635d59044092729de61c2 Terra Address: terra1h958pz06w8chaagclv24z2083x2npgd4659h3p
> 
> Thanks a lot!

Hello, A support ticket has been opened for you with Support ticket number BN5445BN. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by sammiyee** [comment]
> i also bridge a lot ust but never received my money :
> 
> **6,354**.949405 UST = https://bscscan.com/tx/0x07fec9e91050ff2d208dbb3770618e4782c90022c9d803beb7e615f237404f89 **8,474**.860373 UST = https://bscscan.com/tx/0xd6fcc144bc1a326532b0b8141d00ec0ac419bde3d1db107918d7ec50513c2b67 **2,010**.980757 UST = https://bscscan.com/tx/0x4e51c58583219555d462082695db04cea11eb505cc071734fcd948f5f26d9ff4
> 
> my terra address : terra1alq27zlll8at9cv0g059ypf8wqf6q2sdg5j8ta

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by creativefull** [comment]
> Transaction Date Time: May-11-2022 08:28:45 AM +UTC BSC Transaction Hash: 0x527efaa715a5c973cfc053c2f5fae08fd9bfa211cba635d59044092729de61c2 Terra Address: terra1h958pz06w8chaagclv24z2083x2npgd4659h3p
> 
> Thanks a lot!

did u has been receive your UST bro ?

**Comment by sammiyee** [comment]
> Transaction Date Time: May-11-2022 08:28:45 AM +UTC BSC Transaction Hash: 0x527efaa715a5c973cfc053c2f5fae08fd9bfa211cba635d59044092729de61c2 Terra Address: terra1h958pz06w8chaagclv24z2083x2npgd4659h3p
> 
> Thanks a lot!

Hello, A support ticket has been opened for you with Support ticket number BN4554BN. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by yuyan1991** [comment]
> > Transaction Date Time: May-11-2022 08:28:45 AM +UTC BSC Transaction Hash: 0x527efaa715a5c973cfc053c2f5fae08fd9bfa211cba635d59044092729de61c2 Terra Address: terra1h958pz06w8chaagclv24z2083x2npgd4659h3p
> > Thanks a lot!
> 
> did u has been receive your UST bro ?

I received it! It had been token a few hours to receive UST! Good luck!

**Comment by creativefull** [comment]
> > > Transaction Date Time: May-11-2022 08:28:45 AM +UTC BSC Transaction Hash: 0x527efaa715a5c973cfc053c2f5fae08fd9bfa211cba635d59044092729de61c2 Terra Address: terra1h958pz06w8chaagclv24z2083x2npgd4659h3p
> > > Thanks a lot!
> > 
> > 
> > did u has been receive your UST bro ?
> 
> I received it! It had been token a few hours to receive UST! Good luck!

how long bro ? i did'nt receive until now

**Comment by yuyan1991** [comment]
> > > > Transaction Date Time: May-11-2022 08:28:45 AM +UTC BSC Transaction Hash: 0x527efaa715a5c973cfc053c2f5fae08fd9bfa211cba635d59044092729de61c2 Terra Address: terra1h958pz06w8chaagclv24z2083x2npgd4659h3p
> > > > Thanks a lot!
> > > 
> > > 
> > > did u has been receive your UST bro ?
> > 
> > 
> > I received it! It had been token a few hours to receive UST! Good luck!
> 
> how long bro ? i did'nt receive until now

It took me around 3 hours:(

**Comment by creativefull** [comment]
let's me wait until 4 hours :(
