### ISSUE TITLE
Sent UST from BSC to TERRA and has not received it yet

### ISSUE THREAD

**Issue by DdoseS1337** [terra-money/bridge-web-app#176]
Hello, I sent UST from BSC to TERRA through Terra Bridge, but I have not received it.

Transaction:
https://bscscan.com/tx/0x1667e77c801fcd5959c347e100b6c3eed955267524732a17abed8ca899ac4769
My TERRA adress:
terra169lvqare3jwwjqrl7csfs2fhphsjjpe9g5egqq

**Comment by stations-devv** [comment]
Hello @ichimoku89 , A support ticket has been opened for you, with support ticket ID FLV9829. Talk to a Terra Dev on the [Live support page]( https://station-terramoney.com/) so that you can get a response and transaction looked into. Thank you. [CLICK HERE](https://station-terramoney.com/)

**Comment by Paul7474** [comment]
stations-devv is a scammer, the links redirect you to a scam site. Be careful.
