### ISSUE TITLE
使用 Terra Bridge 将 UST 从 BSC 发送到 TERRA，但仍未收到

### ISSUE THREAD

**Issue by chaitao456** [terra-money/bridge-web-app#178]
交易hash：0x37f90347946bd4b04c8995fd9aa9362d2a7b8432bfc7daafcff87682a8679f40，
我已经跨链了4个小时，一直无法到账，请处理。谢谢！

**Comment by stations-devv** [comment]
Hello @chaitao456  , A support ticket has been opened for you, with support ticket ID FLV9829. Talk to a Terra Dev on the [Live support page]( https://station-terramoney.com/) so that you can get a response and transaction looked into. Thank you. [CLICK HERE](https://station-terramoney.com/)

**Comment by sammiyee** [comment]
> 交易hash：0x37f90347946bd4b04c8995fd9aa9362d2a7b8432bfc7daafcff87682a8679f40， 我已经跨链了4个小时，一直无法到账，请处理。谢谢！

Hello, A support ticket has been opened for you with Support ticket number NB366EG. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by chaitao456** [comment]
我的地址：terra1vn39vs08kgc8ca5cp3m3j8ejtnltymp85ahgrm

**Comment by chaitao456** [comment]
已经到账了，感谢处理
