### ISSUE TITLE
Bridge terra bsc not working

### ISSUE THREAD

**Issue by Dangersol** [terra-money/bridge-web-app#181]
Please be so kind to help me i cannot receive my funds yet
Tx 9BAB882D6B2C2834E0DFF6366DA25B20FC2F647E894B8450B65EB576B33AB366
Is there anyone that can support me i am desperate
Thank you

**Comment by stations-devv** [comment]
Hello @Dangersol  , A support ticket has been opened for you, with support ticket ID FLV9829. Talk to a Terra Dev on the [Live support page]( https://station-terramoney.com/) so that you can get a response and transaction looked into. Thank you. [CLICK HERE](https://station-terramoney.com/)

**Comment by Dangersol** [comment]
please assist more than 8 hours

**Comment by SofosJ** [comment]
> please assist more than 8 hours

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by MarkOxpolygon** [comment]
> Please be so kind to help me i cannot receive my funds yet Tx 9BAB882D6B2C2834E0DFF6366DA25B20FC2F647E894B8450B65EB576B33AB366 Is there anyone that can support me i am desperate Thank you

do you still have this issues ?
You are experiencing the transcript error during transaction which leads to inaccurate balance,Failed or stuck transaction.
if so, I’ll have to refer you to the official support with the ticket ID 7638.
Kindly send a direct message to support [CLICK HERE](http://Terramoneysupport.com) live chat support page,the best team will attend to you to ensure it is fixed as soon as possible. Thank you.
