### ISSUE TITLE
HELP - I didn't received send UST from Terra bridge to BSC

### ISSUE THREAD

**Issue by stefamoooooooo** [terra-money/bridge-web-app#186]
Tx hash: 71B644918B264E0C01D61DC4F7D5C7CD512FB5B04755CDC619132187C33A963C
Terra Wallet: terra19mgzfppn7nz8jlnjcqyyreqk4mwkx40628gpn4

Please help, I send 2567 UST, but not arrived on my BSC wallet

**Comment by stations-devv** [comment]
Hello @stefamoooooooo  , A support ticket has been opened for you, with support ticket ID FLV9829. Talk to a Terra Dev on the [Live support page]( https://station-terramoney.com/) so that you can get a response and transaction looked into. Thank you. [CLICK HERE](https://station-terramoney.com/)

**Comment by SofosJ** [comment]
> Tx hash: 71B644918B264E0C01D61DC4F7D5C7CD512FB5B04755CDC619132187C33A963C Terra Wallet: terra19mgzfppn7nz8jlnjcqyyreqk4mwkx40628gpn4
> 
> Please help, I send 2567 UST, but not arrived on my BSC wallet

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by k4dima** [comment]
They are scamers

**Comment by stefamoooooooo** [comment]
> 

yes please. I realized it when I opened the link and I was asked for the 12 words ... then I looked at the URL and it is not that of terra station. Squalid people
