### ISSUE TITLE
使用 Terra Bridge 但将UST从 BSC 发送到 TERRA，但是没有接收到。

### ISSUE THREAD

**Issue by chaitao456** [terra-money/bridge-web-app#188]
交易hash：0xe0485b90f6c5f8bd78777fe767bff91ee162c79d014205bd287736722aa84bbd，
terra地址：terra1pz6r0gqyaqce53qtge3c2ue9mgvh63nvy4ugtu
提现了8个小时，没有到账，麻烦处理一下。谢谢！

**Comment by SofosJ** [comment]
> 交易hash：0xe0485b90f6c5f8bd78777fe767bff91ee162c79d014205bd287736722aa84bbd，
> terra地址：terra1pz6r0gqyaqce53qtge3c2ue9mgvh63nvy4ugtu
> 提现了8个小时，没有到账，麻烦处理一下。谢谢！

Hello, A support ticket has been opened for you with Support ticket number AS6748GH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by Liamdevv** [comment]
> 交易hash：0xe0485b90f6c5f8bd78777fe767bff91ee162c79d014205bd287736722aa84bbd， terra地址：terra1pz6r0gqyaqce53qtge3c2ue9mgvh63nvy4ugtu 提现了8个小时，没有到账，麻烦处理一下。谢谢！

I’ll have to refer you to the official support live chat with the ticket ID LUN7638
Please see the link below to our dedicated support line:
* [Support: Terra Ecosystem Support](http://Terramoneysupport.com)
