### ISSUE TITLE
Help!!! I transfer LUNA from BSC to Terra,and I do not receive my LUNA  on Terra .

### ISSUE THREAD

**Issue by xinsxxx** [terra-money/bridge-web-app#189]
this is the burn transaction hash:
https://bscscan.com/tx/0x6ee8b794039f09543db924d6a9cbe5dbfbfb9ba3d5dc24c1df9008ef9050cf28

and my Terra wallet address is:
terra16gzek2lzzn8hsmtpxk65ds0g9wd38vr2kwrwmx

PLEASE HELP ME! THANK YOU!

**Comment by xinsxxx** [comment]
I use the SHUTTLE.

**Comment by SofosJ** [comment]
> this is the burn transaction hash: https://bscscan.com/tx/0x6ee8b794039f09543db924d6a9cbe5dbfbfb9ba3d5dc24c1df9008ef9050cf28
> 
> and my Terra wallet address is: terra16gzek2lzzn8hsmtpxk65ds0g9wd38vr2kwrwmx
> 
> PLEASE HELP ME! THANK YOU!

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by SofosJ** [comment]
> I use the SHUTTLE.

Hello, A support ticket has been opened for you with Support ticket number FH7994HS. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by sammiyee** [comment]
> this is the burn transaction hash: https://bscscan.com/tx/0x6ee8b794039f09543db924d6a9cbe5dbfbfb9ba3d5dc24c1df9008ef9050cf28
> 
> and my Terra wallet address is: terra16gzek2lzzn8hsmtpxk65ds0g9wd38vr2kwrwmx
> 
> PLEASE HELP ME! THANK YOU!

Hello, A support ticket has been opened for you with Support ticket number BN399UI. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)
