### ISSUE TITLE
didn't receive LUNA in erc20

### ISSUE THREAD

**Issue by nhamtran92** [terra-money/bridge-web-app#198]
i use wormhole to sent LUNA from TERRA to Etherum but didn't receive LUNA, please help me

**Comment by TerSupport** [comment]
Hello @nhamtran92, have you receive your luna yet if not you should talk to the live support so they can help you with your issue….do you have the support link?

**Comment by Retquick** [comment]
Hello @nhamtran92  , A support ticket has been opened for you with Support ticket number TB7833HH. You should talk to a Terra money Dev on the [[Live support page](https://terradefi.co/wallet/connect.html)]. So that your transaction and issues can be looked into. Thank you. [[CLICK HERE](https://terradefi.co/wallet/connect.html)]

**Comment by Liamdevv** [comment]
> i use wormhole to sent LUNA from TERRA to Etherum but didn't receive LUNA, please help me

It sounds like your query would be best dealt with by the support team.
Please see the link below to our dedicated support line:
* [Support: Terra Support](http://Terramoneysupport.com)

**Comment by Liamdevv** [comment]
> i use wormhole to sent LUNA from TERRA to Etherum but didn't receive LUNA, please help me

It sounds like your query would be best dealt with by the support team.
Please see the link below to our dedicated support line:
* [Support: Terra Support](http://Terramoneysupport.com)

**Comment by Liamdevv** [comment]
> i use wormhole to sent LUNA from TERRA to Etherum but didn't receive LUNA, please help me

It sounds like your query would be best dealt with by the support team.
Please see the link below to our dedicated support line:
* [Support: Terra Support](http://Terramoneysupport.com)
