### ISSUE TITLE
Bridge from Harmony, tokens missing

### ISSUE THREAD

**Issue by michaelotis** [terra-money/bridge-web-app#48]
Bridged UST from Harmony to Terra, tokens were burned on Harmony but never arrived at Terra address

TX: https://explorer.harmony.one/tx/0xbf8ec13869d27aebdea20b497243caaf4011635c4aca9409a1a07798e36d3e25

Terra address: terra17ju3gnk47nxzqm0ard37ezqx43rdsg0g6j73vk

Amount 294.487152 UST

**Comment by skqksh** [comment]
https://finder.terra.money/columbus-4/tx/A2986FA1D0D33665E01AF72F039BAD36225C864F07309F2B4F8AA07039CE61BB
