### ISSUE TITLE
Error: "Ethereum Whitelist Json" data does not exist message on terra bridge website

### ISSUE THREAD

**Issue by attitude928** [terra-money/bridge-web-app#51]
An Error: "Ethereum Whitelist Json" data does not exist message appeared on the terra bridge website this morning
Now I can't use the bridge
I may have caused this when trying to set up a Celo Ledger wallet & trying to connect to celo node
Any quick fix?
Any precautions or hack concerns?
Thanks

**Comment by skqksh** [comment]
Network status can occur that problem, just refresh it.
