### ISSUE TITLE
Accidentally sent UST to terra bridge from Coinbase Pro

### ISSUE THREAD

**Issue by danlikespez** [terra-money/bridge-web-app#57]
Hello, I don't know if anyone can help but I accidentally sent UST from my Coinbase Pro account to Terra bridge by using the ethereum UST address: 0xa47c8bf37f92aBed4A126BDA807A7b7498661acD that I copied from the Terra bridge. Transaction hash: 0x2df95e9510a3355a34db465bd09c798d7de8a0796208019261402471076cee7d. My metamask wallet is: 0x2F373b6126198cDD3165Cc8A0Be183e15637017C.

I would appreciate any help. I understand it was my mistake and I will take the loss.
Thank you

**Comment by mpthomas** [comment]
@danlikespez were you able to get this resolved?

**Comment by danlikespez** [comment]
No nothing. Don’t know who else to contact…

**Comment by mpthomas** [comment]
Someone on the discord for Mirror commented to me that it wasn't possible. Adding some basic js to check for this condition would seem relatively straight forward. I'd like to hear feedback from the team on adding this type of check to prevent issues like ours in the future.

**Comment by skqksh** [comment]
I'm really sorry. I checked if you can get back UST but it's impossible to return it 😭
