### ISSUE TITLE
Accidentally Sent UST To Default Token Address

### ISSUE THREAD

**Issue by mpthomas** [terra-money/bridge-web-app#58]
I'm not sure if this is possible, but I meant for the below transaction to be sent to my Ethereum wallet. Any assistance would be greatly appreciated. I'll obviously cover any associated gas fees.

https://finder.terra.money/columbus-4/tx/A8860502A8F1E4FC2D59437DFD76FBF47F930E9B7DE8F33B5B7AF5A31732C206

Terra: terra1e2sgw8fd86djcnuwq9rypyu3djeg0ukpkjqdfj
Ethereum: 0xEAF1EaF9A95c7f1c37bCEeAF49423dccDEBFc6E1

**Comment by skqksh** [comment]
I'm really sorry. I checked if you can get back UST but it's impossible to return it
