### ISSUE TITLE
Terra Bridge is down

### ISSUE THREAD

**Issue by hr11111** [terra-money/bridge-web-app#60]
Hi, 
I cannot access Terra Bridge anymore. When I get to landing page I get an "Shuttle Pairs Json"....Then a redirected "402: Payment_required" followed by "This deployment has been disabled" "Code: 'Deployment_Disabled' "

Are ISPs blocking this? Even VPN workaround not working.

**Comment by hanjukim** [comment]
Thanks for the report. We are dealing with it right now. Vercel is blocking it to be served and we are moving it to CloudFlare right now. It will be available in couple hours (maybe less than 30 minutes)

**Comment by hr11111** [comment]
Thanks!
