### ISSUE TITLE
UST to ETH using TERRA Bridge

### ISSUE THREAD

**Issue by protostar210** [terra-money/bridge-web-app#62]
I went to transfer some of my UST to ETH and have the ETH deposit to my Coinbase wallet. The bridge says it worked however I never received my ETH. I feel I've lost my funds and don't know what to do. Can anyone help?

**Comment by protostar210** [comment]
Wait... I don't know what happened now but its in my Coinbase account as UST, I think I see what the bridge does now. It was just unclear for me because it was the first time I used it.  I think I got lucky this time.

**Comment by YunSuk-Yeo** [comment]
good :)
