### ISSUE TITLE
Terra bridge - UST from terra station to metamask wallet

### ISSUE THREAD

**Issue by Skeju** [terra-money/bridge-web-app#63]
Hi. I sent the UST from my terra station wallet to metamask wallet through terra bridge. I chose that the tokens should have been sent from TERRA to BSC. I put my wallet address and clicked confirm. Unfortunately tokens didn't appear on my metamask wallet and they disappeared from my terra station wallet. What have I done wrong? Any help will be much appreciated.

**Comment by Omar-Aziz** [comment]
> Hi. I sent the UST from my terra station wallet to metamask wallet through terra bridge. I chose that the tokens should have been sent from TERRA to BSC. I put my wallet address and clicked confirm. Unfortunately tokens didn't appear on my metamask wallet and they disappeared from my terra station wallet. What have I done wrong? Any help will be much appreciated.

@Skeju go on https://apeboard.finance/dashboard and search for the BSC destination wallet address you provided when you bridged UST. From there you can see all assets that are in that wallet address. 

Metamask is just an app that lets you view your assets and execute transactions. Your actual wallet is the address. Sometimes the asset is in your wallet but Metamask is just not showing it.

**Comment by YunSuk-Yeo** [comment]
Please reopen the issue if you still have problem with your txid :)
