### ISSUE TITLE
Bridged MIR from BSC to Terra - no funds...

### ISSUE THREAD

**Issue by ajss77** [terra-money/bridge-web-app#67]
I tried to bridged some MIR from BSC to Terra and I only see a big zero there.

BSC transaction hash:

0xd608e78db8d715131da5e78b03bc475f576717a3be96a59eb323189e48b02e32

On Terra Finder I see a transaction with that exact value...but it isn't my account:

139BA0BDA2507A32CEE6BAE161D515E7D2EDFCCC5C1E7B9A5513498991581627

How can this be reverted?
I put the right address (copy and paste), so it wasn't a mistake made by me.

**Comment by skqksh** [comment]
I'm sorry but It seems you input MIR address as a destination address, not your address.
we checked your tx hash on the network

**Comment by YunSuk-Yeo** [comment]
I think you sent your MIR to MIR token contract address, and it is not recoverable...

sorry to see this... :(
