### ISSUE TITLE
Issues Bridge from Terra to BSC

### ISSUE THREAD

**Issue by PeterMS93** [terra-money/bridge-web-app#69]
Sent 10 Luna through Terra Bridge -> https://finder.terra.money/columbus-5/tx/D5D251BB443141F6C0AE1D2419CF591F1402AD80E030A84AAC6D2A58AF3DD984

Did not received any token at my wallet 0x04E4c0Ef04aDe373abA14546BE454c46971eCdC0

Please reply Asap

Thanks
Pietro

**Comment by zjuchenyuan** [comment]
It seems the bridge send your luna to your eth wallet: https://etherscan.io/address/0x04E4c0Ef04aDe373abA14546BE454c46971eCdC0

You can do these things to recover your fund: (Not finance advice)
- Send ETH to your wallet (same address but choose Ethereum as the withdraw chain), and then transfer LUNA to a supporting CEX to sell
- Maybe flashbot can help you transfer without you paying ETH using this address

**Comment by YunSuk-Yeo** [comment]
already sent https://etherscan.io/tx/0xf07c051e97afcf29560cc836304b9c20f05d3f60a8b3d0e376bdc236def11fb2
