### ISSUE TITLE
remittance error

### ISSUE THREAD

**Issue by lim3185** [terra-money/bridge-web-app#73]
Please return the UST deposited to the smart contract address
![Screenshot_20211024-051939_Chrome](https://user-images.githubusercontent.com/80979800/138571000-6e8798dc-04de-4e01-bc85-2cdee7817cdc.jpg)
![Screenshot_20211024-052005_Chrome](https://user-images.githubusercontent.com/80979800/138571003-493e6055-4418-485d-b456-7adaf7812a73.jpg)
#

**Comment by YunSuk-Yeo** [comment]
Seems relayed

```
[BSC] TERRA => BSC
Sender: terra1z9hcncypw79let00nqjqr4llg2zqw77ttfckqr
To:     0x23396cF899Ca06c4472205fC903bDB4de249D6fC

Requested: 5515.000000 UST
Amount:    5509.485000 UST
Fee:       5.515000 UST

Terra TxHash: 631C053A00F2FE92A867D7B924F34B53942750C01F95D0C3E0F44F379CE18855
BSC TxHash:   0xb79b484a17aa51fe84053bad4209043dd6af8aaf5592459376480f7ac22dd3b4
```

https://bscscan.com/tx/0xb79b484a17aa51fe84053bad4209043dd6af8aaf5592459376480f7ac22dd3b4
