### ISSUE TITLE
Issue UST from TERRA to HARMONY 

### ISSUE THREAD

**Issue by JDRJ22** [terra-money/bridge-web-app#76]
A transfer of UST from terra to harmony chain is not shown on my wallet. 
First, I tried to send a small amount of UST using the bridge and it worked very fast, then, I repeated (48 hours ago aprox) the same with a bigger amount and they never arrived at my wallet. I checked that the transaction was successful.
Is there any problem with the bridge? How can i track where the UST went?

**Comment by OGmacdaddytrilltrill** [comment]
Any luck? I’m having the same issue

**Comment by YunSuk-Yeo** [comment]
Please post txid here.
