### ISSUE TITLE
15 ETH transfer went wrong

### ISSUE THREAD

**Issue by xdrive01** [terra-money/bridge-web-app#78]
I would appreciate any help.

I tried to sent 15 bETH from Terra to Ethereum via Terra Bridge on Oct 28th. 

The transaction hash (Terra) is 
B0C5828C2E4A140F473E65570374C587E9F506A3926AC19A1C8DA03044FDC058

The bETH never arrived at the destination adress. I tried to find the regarding transaction hash on Ethereum blockchain but can't find anything there.

Thanks for any support.

Greets
J.

**Comment by YunSuk-Yeo** [comment]
Seems relayed

```
[MAINNET] TERRA => ETH
Sender: terra1k3s5xjw9urfy9tttuhmag4w67n2qkfnhxsuze9
To:     0x9f389284B2E1Be0Fa905B63d287f76aF71518d15

Requested: 15.000000 bETH
Amount:    14.985000 bETH
Fee:       0.015000 bETH

Terra TxHash: B0C5828C2E4A140F473E65570374C587E9F506A3926AC19A1C8DA03044FDC058
ETH TxHash:   0xaa220691055348c171e996f2edfe46f3cb31c97171b5093877766e28f5f8aeaf
```

https://etherscan.io/tx/0xaa220691055348c171e996f2edfe46f3cb31c97171b5093877766e28f5f8aeaf
