### ISSUE TITLE
UST never arrived from Harmony to Terra

### ISSUE THREAD

**Issue by wyodude** [terra-money/bridge-web-app#79]
Hi there.
A friend of mine have sent some UST, using TerraBridge, from Harmony to Terra.
The funds never made it to Terra Station Wallet.
Here is the transaction hash:
0x268338dd270a530a8943bc707f61db25023a71c839092da4df2773f4e364f854

Would someone be so kind to advice on the solution.
Thank you in advance.

**Comment by wyodude** [comment]
Hello again.
Ca I get a reply?

**Comment by YunSuk-Yeo** [comment]
@wyodude here is your tx recovered https://finder.terra.money/mainnet/tx/AF256760F9CB4F6512341BECF816BC6DA0DA292AB7056B00A0CA5B344D149516

**Comment by wyodude** [comment]
Thank you
