### ISSUE TITLE
UST never arrived Terra - Harmony bridge

### ISSUE THREAD

**Issue by alexboxtel** [terra-money/bridge-web-app#80]
solved.

**Comment by alexboxtel** [comment]
Strange thing is i filled in my MM wallet as receiver but in the transaction this adres is filled in as a Memo. When i check the receivers adres i find a wallet with millions inside, that could be a Terra bridge address

**Comment by OGmacdaddytrilltrill** [comment]
Do you mind letting me know how you solved it? I’m having the same issue.

**Comment by Coinquest1** [comment]
Please let us know HOW this was resolved....ty

**Comment by OGmacdaddytrilltrill** [comment]
It wasn’t. Only have a dollar fifty stuck, but still.

**Comment by YunSuk-Yeo** [comment]
Can you post txid??

**Comment by Coinquest1** [comment]
TX completed days ago 🙂Sent from my Galaxy
-------- Original message --------From: yys ***@***.***> Date: 11/24/21  1:52 PM  (GMT-05:00) To: terra-money/bridge-web-app ***@***.***> Cc: Coinquest1 ***@***.***>, Comment ***@***.***> Subject: Re: [terra-money/bridge-web-app] UST never arrived Terra - Harmony bridge (Issue #80) 
Can you post txid??

**Comment by YunSuk-Yeo** [comment]
Okay let me close the issue.

**Comment by Coinquest1** [comment]
TySent from my Galaxy
-------- Original message --------From: yys ***@***.***> Date: 11/24/21  2:02 PM  (GMT-05:00) To: terra-money/bridge-web-app ***@***.***> Cc: Coinquest1 ***@***.***>, Comment ***@***.***> Subject: Re: [terra-money/bridge-web-app] UST never arrived Terra - Harmony bridge (Issue #80) 
Okay let me close the issue.
