### ISSUE TITLE
sent UST from terra to bsc ; still not receive UST

### ISSUE THREAD

**Issue by Gutcha** [terra-money/bridge-web-app#81]
Hi, I sent 2 UST from terra to my metamask (BSC). It still not arrive. Please kindly check and suggest. Thx.
https://finder.terra.money/columbus-5/tx/B673A2EE77F62E16D0D03021F0D9DF25E681C72F4CA8E6170D080C9C3DFE406A

**Comment by YunSuk-Yeo** [comment]
https://bscscan.com/tx/0xf011ee69a3a2174e1d88938efef19a2479ef8055226ac5204f740d3d084f38c5
