### ISSUE TITLE
No one responding to Terra Bridge issues

### ISSUE THREAD

**Issue by OGmacdaddytrilltrill** [terra-money/bridge-web-app#82]
What’s going on? Why hasn’t anyone addressed all these incomplete transfers? I’m having an issue completing a transfer from Terra to Harmony and no one with Harmony or Terra seems to care.

**Comment by bowie91** [comment]
experiencing the same thing right now

**Comment by YunSuk-Yeo** [comment]
Can you post txid?? I can check the relay result.
