### ISSUE TITLE
TerraBridge glitch (?)

### ISSUE THREAD

**Issue by Coinquest1** [terra-money/bridge-web-app#83]
I used the bridge early this morning to send UST from harmony to Terra. The funds (10 hours later) have not shown up in my Terra wallet. I'm really concerned as i see this is a common complaint. I sent an email to bridge@harmony.one as i was told and have not seen a fix to this issue. If someone has the fix, please reply...thank you

**Comment by YunSuk-Yeo** [comment]
Please post your txid here
