### ISSUE TITLE
Lost my MIR tokens on Terra-BSC bridge

### ISSUE THREAD

**Issue by AllenLau882** [terra-money/bridge-web-app#85]
Haven’t receive MIR token after I sent from Terra chain to BSC chain using Terra Bridge. It has been a week.

Transaction hash：
ACFCB7BDB487E032B7C5449FA69B0BE1A22BB6B499D88FA1B2DE6634650A3310

Thank You so much！

**Comment by YunSuk-Yeo** [comment]
```

[BSC] TERRA => BSC
Sender: terra1d9xp8ue53v9dz0628tepl0tph3wqvujg3n7p5l
To:     0x027Ac35630E42d9DBF93DB2b0E9b205C6C480f32

Requested: 242.526320 MIR
Amount:    242.234774 MIR
Fee:       0.291545 MIR

Terra TxHash: ACFCB7BDB487E032B7C5449FA69B0BE1A22BB6B499D88FA1B2DE6634650A3310
BSC TxHash:   0xdfc5ccd9867a1564625b3beac38149dea8a7536b8456a9f060096544cee0f18b

```

https://bscscan.com/tx/0xdfc5ccd9867a1564625b3beac38149dea8a7536b8456a9f060096544cee0f18b
