### ISSUE TITLE
LUNA was never sent to my account after transaction completed with bridge

### ISSUE THREAD

**Issue by tomdifi** [terra-money/bridge-web-app#86]
Here is the "completed" transaction, but my luna never showed in my wallet.

https://etherscan.io/tx/0x7fb27c7135175c7efcaac878b153b559f2257fd013f45a70855bc059fcdd6c6a

**Comment by YunSuk-Yeo** [comment]
Why did you send the fund to luna token contract?? You should execute burn to relay it to Terra.

Unfortunately it is not recoverable.
