### ISSUE TITLE
Urgent! $10k lost in bridge.  "cannot estimate gas"

### ISSUE THREAD

**Issue by kcsf** [terra-money/bridge-web-app#87]
![image](https://user-images.githubusercontent.com/17506215/142734451-c28bb87c-d690-45df-9b41-acab42097e0b.png)

Bridging UST from ETH to Terra - after transaction confirmed on Metamask/Ledger, terrabridge returns error:

------------------------
cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32603,"message":"execution reverted: ERC20: burn amount exceeds balance","data":{"originalError":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002245524332303a206275726e20616d6f756e7420657863656564732062616c616e6365000000000000000000000000000000000000000000000000000000000000","message":"execution reverted: ERC20: burn amount exceeds balance"}}}, method="estimateGas", transaction={"from":"0x41D6a8Bf6178095509f4bDbB532F30bCdb7BBCbA","to":"0xa47c8bf37f92aBed4A126BDA807A7b7498661acD","data":"0xbcf64e0500000000000000000000000000000000000000000000021e19e0c9bab240000020bb008fc0581b3e3dc94af66fba2438a1f973cd000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.4.3)
------------------------

10k burned: https://etherscan.io/tx/0x939b20e5c5185086ceaba2a9d834d003e2e3f68ba0ed5618b85bcd4b4e7e8050

What do I do?

**Comment by YunSuk-Yeo** [comment]
I think your fund sent to your destination address

```
[MAINNET] ETH => TERRA
Sender: 0x41D6a8Bf6178095509f4bDbB532F30bCdb7BBCbA
To:     terra1yzaspr7qtqdnu0wfftmxlw3y8zslju7dg34ael

Requested: 10000.000000 UST
Amount:    10000.000000 UST
Fee:       0.000000 UST

ETH TxHash:   0x939b20e5c5185086ceaba2a9d834d003e2e3f68ba0ed5618b85bcd4b4e7e8050
Terra TxHash: 61DE566C0C545708A22EE7BA2A1DF9B545E555C34E4F75CC4888039408620A33
```

https://finder.terra.money/mainnet/tx/61DE566C0C545708A22EE7BA2A1DF9B545E555C34E4F75CC4888039408620A33
