### ISSUE TITLE
Plz Hellp! UST lost at bridge!

### ISSUE THREAD

**Issue by loznkazagithub** [terra-money/bridge-web-app#88]
I bridged 6500k UST from Terra to Harmony using terra bridge. Than, I tried to bridge 6493.5 UST back. Transaction went true but i didn't get any UST in my Terra station.

https://explorer.harmony.one/tx/0x3ec62e96539cce96d2e8368ada0e9842ffe762d2563c45f46f16e8356cc2a91a

Can somebody please help me!

**Comment by bowie91** [comment]
https://explorer.harmony.one/block/0x4368bceea9eb4697681f3ec699f1367e354ac81eb857c960acd058b0f2d3c589

**Comment by YunSuk-Yeo** [comment]
Seems relayed 
```
[HMY] HMY => TERRA
Sender: 0xB5dEC8eE76B489D4ed2eC43C1029CBC095005452
To:     terra1axemajvrwg49554rjuxck80vqm8xy5qqlcua9j

Requested: 6493.500000 UST
Amount:    6493.500000 UST
Fee:       0.000000 UST

HMY TxHash:   0x3ec62e96539cce96d2e8368ada0e9842ffe762d2563c45f46f16e8356cc2a91a
Terra TxHash: BD9AF7D49E8E381582E67E5B2C0197E3BAF3356CF54236B0781F64323CF3264C
```

https://finder.terra.money/mainnet/tx/BD9AF7D49E8E381582E67E5B2C0197E3BAF3356CF54236B0781F64323CF3264C
