### ISSUE TITLE
UST lost in space... 

### ISSUE THREAD

**Issue by bowie91** [terra-money/bridge-web-app#89]
harmony side sent 900 UST wrapped, terra bridge never registered or received it. Please help 

https://finder.terra.money/mainnet/address/terra1rtn03a9l3qsc0a9verxwj00afs93mlm0yr7chk

https://explorer.harmony.one/block/0x4368bceea9eb4697681f3ec699f1367e354ac81eb857c960acd058b0f2d3c589

**Comment by YunSuk-Yeo** [comment]
Can you post txid here?

**Comment by bowie91** [comment]
tx hash: 9F985C049C683E05EBF066C9738C2F5771BE1B905CD74FEA15907F67C8BFC834

**Comment by bowie91** [comment]
tx hash: D35B286F34E7B1E549B2B4FF636DD87329096A6A930744A4A9F022E9FCFA9228

**Comment by bowie91** [comment]
tx hash: 9F985C049C683E05EBF066C9738C2F5771BE1B905CD74FEA15907F67C8BFC834

**Comment by bowie91** [comment]
What do you mean by tx id?

**Comment by YunSuk-Yeo** [comment]
In this transaction https://finder.terra.money/mainnet/tx/9F985C049C683E05EBF066C9738C2F5771BE1B905CD74FEA15907F67C8BFC834, you sent your fund to https://finder.terra.money/mainnet/address/terra17p6wnssgyq8dxqnlzkd0urzemu0vlf9ckvlyz7 address. 

It is not shuttle address...

**Comment by YunSuk-Yeo** [comment]
> What do you mean by tx id?

your relay tx hash want to recover.

**Comment by bowie91** [comment]
hash: 0xe2b391ea5692e50d65919c4f3982fa96e7c18084e77db29871065aad71302c01

eth hash: 0x61f736020445997d83bbad9aa2816401a5dc10729973db3e1f724e8b44ba439e

**Comment by bowie91** [comment]
https://explorer.harmony.one/tx/0x61f736020445997d83bbad9aa2816401a5dc10729973db3e1f724e8b44ba439e?activeTab=0

**Comment by bowie91** [comment]
the total value is 900 UST, sent from harmony to terra

**Comment by YunSuk-Yeo** [comment]
@bowie91 recovered https://finder.terra.money/mainnet/tx/E7132D6A72E837DDDE211242AB5E60117EFE85D09DA0AB4D9D39D4DAEC8E724B

**Comment by bowie91** [comment]
on harmony side it went through, but terra received no input

**Comment by YunSuk-Yeo** [comment]
all good?

**Comment by bowie91** [comment]
YES!!! Thank you so so much

**Comment by bowie91** [comment]
amazing
