### ISSUE TITLE
Sent Luna to BSC Explicitly, wound up on ETH - So I guess it's farming now huh?

### ISSUE THREAD

**Issue by Alchemyst0x** [terra-money/bridge-web-app#90]
Seriously. Tag your app as alpha or whatever is appropriate. Every issue in here is the same practically - either funds disappearing, taking forever to appear again, or winding up on the wrong blockchain. It would be one thing if it was an accidental swap to say, Matic, or hell, xDai, or literally anything but ETH. But who is going to pay for the gas fees from ETH? And this bridge is linked directly from Terra Station Chrome AddOn.

Remove the link. Fix your app. It's pretty unreasonable to have this kind of a performance issue and not even respond let alone compensate for the issue, although I'll concede how ridiculous that would be - to expect the devs here to pay ETH ERC20 TX fees. I am going to have to stare at $50 in LUNA for months now, just hanging out in my ETH wallet. While I am bullish on LUNA anyway, and sure it's not much - it's $50 less than I want to pay of the $70 transaction fees it would take just to send the stupid ERC20 to an exchange let alone swap it.

Massive annoyance. 

EDIT: For anyone reading this, in part due to the spontaneously mildly-reasonable fees on ETH tonight (68 GWEI is what I am seeing at the time of writing, vs the usual 120+) as well as making use of a service that doesn't tax their ETH withdraws aside from the TX fee & another service - which unless I am mistaken is pretty much developed/spawned of the same devs, I was able to transfer the LUNA from wrapped LUNA back to my Terra Station wallet by doing the following steps:

1. I swapped BSC (smart-chain) BNB for ETH on https://fixedfloat.com/ (unavailable to those in the US or without a VPN). I sent about 0.04 BNB, equal to about $25, and ended up paying around a $9 TX fee for that initial swap
2. I utilized the service I mentioned (also [?] developed by Mirror Protocol) to connect my MetaMask containing the wrapped LUNA to their service, which can be found at https://eth.mirror.finance/my
3. After connecting my MetaMask, I clicked on the "My Page" link and there's a little 3-dots menu clickable with the option to send your LUNA to another ETH or TERRA chain address, so I input my Terra Station address and ended up paying about $11 in fees this route. 

So while I have long abandoned ETH and even given up on most of the Layer 2 stuff that's available as of right now, I suspect both these options are going to be cheaper than most. And while I spent about $20 just to recover a $50 or so in LUNA, I can see where this would be a very valuable solution for individuals having less-fortunately made a mini-fortune of a transaction size only to have this crap happen to them too. So hopefully this helps someone.

Also edited my original comments to remove the language used; apologies, really ticked me off at the time though. I stand by the comment to remove that link from the Chrome App or contact whomever can. Seriously not fun. And please get someone on these issues, or at least write something in the docs, give a solid warning, anything more would be fantastic short of fixing the problem!

**Comment by devhyunjae** [comment]
Added a fix
