### ISSUE TITLE
Wormhole transfer 

### ISSUE THREAD

**Issue by bowie91** [terra-money/bridge-web-app#92]
42A1AC9025FC1B5DA1C0BACE36A4A389C0839A3CF8CD51BD072EB7BC4DEF6247

lost 680 USTs. Cant redeem

**Comment by YunSuk-Yeo** [comment]
Tx seems failed, please check https://finder.terra.money/mainnet/tx/42a1ac9025fc1b5da1c0bace36a4a389c0839a3cf8cd51bd072eb7bc4def6247

and our web app did not support wormhole yet
