### ISSUE TITLE
I never recieved the money, please HELP!

### ISSUE THREAD

**Issue by AldasoroS** [terra-money/bridge-web-app#94]
This is the tx

https://finder.terra.money/columbus-5/tx/B95AF569E85CD5084505C871033B33B63B94B7F52AE1A20583AC688853A17BCA

I never got the money in my wallet, please help!

**Comment by YunSuk-Yeo** [comment]
Seems your fund is here https://etherscan.io/tx/0x1639565435e154919320bbcccf2c27f7d2169beb95ac322768e8815a5847abd9

The recipient address is Ethereum shuttle address.
