### ISSUE TITLE
Not receive money (Terra to BSC)

### ISSUE THREAD

**Issue by Jinnieeee** [terra-money/bridge-web-app#95]
https://finder.terra.money/columbus-5/tx/9FB912A78C1E3C51F7574C4F3C83913C38BCB447E62DDA0BC489441203403374

Please help

**Comment by zither-dogged0g** [comment]
Seems like it did arrive: https://bscscan.com/tx/0xb2e206c8f50fb3e0cbef505863fe3a7d4598fecebff38c2a6c4f6761779fb79d.

**Comment by Jinnieeee** [comment]
thank you!
