### ISSUE TITLE
UST never arrived after bridging from Terra to BSc

### ISSUE THREAD

**Issue by zither-dogged0g** [terra-money/bridge-web-app#96]
I bridged 1327.253045 UST to BSc on the following transaction (below), however, the funds never arrived.

@YunSuk-Yeo, you seem to have been able to fix it for others. Would you please have a look? Also, consider adding a "Degraded Services" page.

Edit: it did arrive now.

**Comment by YunSuk-Yeo** [comment]
Please post txid,

during weekend BSC network was unstable, so many transactions are delayed. maybe you already received. 

If not arrived, please post your txid here.

**Comment by cryptopunks6690** [comment]
> I bridged 1327.253045 UST to BSc on the following transaction (below), however, the funds never arrived.
> 
> @YunSuk-Yeo, you seem to have been able to fix it for others. Would you please have a look? Also, consider adding a "Degraded Services" page.
> 
> Edit: it did arrive now.

Hello @zither-dogged0g   , You should talk to a Terra money Dev on the [Live support page](https://agoraterra.org/). So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.org/)
