### ISSUE TITLE
Bridge from Terra to BSC money never arrived

### ISSUE THREAD

**Issue by defury-luna** [terra-money/bridge-web-app#98]
I bridged UST from terra to bsc but funds never arrived:

Edit 1:OK after reading the others issue i have check the etherium chain of my wallet and i have find my ust...

Edit 2: Nice over 30 $ for send back (charging eth wallet ecc ecc)... lets hope going to the right chain now

The service is nice but 2 sends all 2 to the wrong chain.....

**Comment by YunSuk-Yeo** [comment]
Okay I will request to web devs to check this problem.

**Comment by YunSuk-Yeo** [comment]
btw duplicated so close this issue #90
